name: PR update

on: push

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update all prs
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
